### ISSUE TITLE
Error after installing package

### ISSUE THREAD

**Issue by EdwardOkech** [krstffr/meteor-sitemap-creator#1]
Am having errors after installing package, 

```
ReferenceError: sitemaps is not defined
W20160129-05:59:34.187(3)? (STDERR)     at /home/okech/projects/web/realestate1/.meteor/local/build/programs/server/app/server/sitemaps.js:9:1
W20160129-05:59:34.187(3)? (STDERR)     at /home/okech/projects/web/realestate1/.meteor/local/build/programs/server/app/server/sitemaps.js:35:4
W20160129-05:59:34.187(3)? (STDERR)     at /home/okech/projects/web/realestate1/.meteor/local/build/programs/server/boot.js:242:10
W20160129-05:59:34.188(3)? (STDERR)     at Array.forEach (native)
W20160129-05:59:34.188(3)? (STDERR)     at Function._.each._.forEach (/home/okech/.meteor/packages/meteor-tool/.1.1.10.11l26ze++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160129-05:59:34.188(3)? (STDERR)     at /home/okech/projects/web/realestate1/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8

```

now my project is messed up tried removing the package but still encountering the same error

**Comment by krstffr** [comment]
It seems you have an undefined `var`/`let`/`const` called `sitemaps` in the file `sitemaps.js`?

**Comment by EdwardOkech** [comment]
Hi Kristffr...i actualy found out that the error was actualy not as a result of krstffr:meteor-sitemap-creator, i had another sitemap package that i had not uninstalled causing all this issues..sorry for the confusion.

**Comment by krstffr** [comment]
Ni problem!
